# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy a Container

on:
  workflow_call:
    secrets:
      DOCKER_PROJECT_ID:
        required: true
      DOCKER_SA_KEY:
        required: true
      GCP_SG_DEV_PROJECT:
        required: true
      GCP_SG_DEV_SA_KEY:
        required: true
      GCP_AU_DEV_PROJECT:
        required: true
      GCP_AU_DEV_SA_KEY:
        required: true
      REGION_SINGAPORE:
        required: true
      REGION_SYDNEY:
        required: true

env:
  DOCKER_PROJECT_ID: ${{ secrets.DOCKER_PROJECT_ID }}
  DOCKER_SA_KEY: ${{ secrets.DOCKER_SA_KEY }}
  SG_PROJECT_ID: ${{ secrets.GCP_SG_DEV_PROJECT }}
  SG_SA_KEY: ${{ secrets.GCP_SG_DEV_SA_KEY }}
  AU_PROJECT_ID: ${{ secrets.GCP_AU_DEV_PROJECT }}
  AU_SA_KEY: ${{ secrets.GCP_AU_DEV_SA_KEY }}
  REGION_SINGAPORE: ${{ secrets.REGION_SINGAPORE }}
  REGION_SYDNEY: ${{ secrets.REGION_SYDNEY }}
  SERVICE: ToolJet

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK for DockerHub
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.DOCKER_PROJECT_ID }}
          service_account_key: ${{ secrets.DOCKER_SA_KEY }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia.gcr.io

      - name: Build and Push Container
        run: |-
          DOCKER_BUILDKIT=1 docker buildx build --platform=linux/amd64 -f docker/production.Dockerfile -t asia.gcr.io/${{ env.DOCKER_PROJECT_ID }}/${{ env.SERVICE }}:monorepo-${{  github.sha }} .
          docker push asia.gcr.io/${{ env.DOCKER_PROJECT_ID }}/${{ env.SERVICE }}:monorepo-${{  github.sha }}

      - name: Setup Cloud SDK for Deployment to Singapore
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.SG_PROJECT_ID }}
          service_account_key: ${{ env.SG_SA_KEY }}
          export_default_credentials: true # Set to true to authenticate the Cloud Run action

      - name: Deploy to Cloud Run in Singapore
        id: deploy_sg
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ env.SERVICE }}
          image: asia.gcr.io/${{ env.DOCKER_PROJECT_ID }}/${{ env.SERVICE }}:monorepo-${{  github.sha }}
          region: ${{ env.REGION_SINGAPORE }}

      - name: Show Output for Singapore
        run: echo ${{ steps.deploy_sg.outputs.url }}
